---
title: "Task4Questions"
author: "Hannah Cope"
date: "9/8/2021"
output: html_document
---

##DPLRY Practice
```{r}
#Convert the iris data to a tibble called iris_data.
iris_data <- tibble(iris)
iris_data  

#Arrange the iris data by Sepal.Length and display the first ten rows.
sepal_length <- arrange(iris_data, Sepal.Length)
head(sepal_length, n = 10)

#Select the Species and Petal.Width columns and put them into a new data set called testdat.
testdat <- select(iris_data, Species, Petal.Width)
testdat

#Create a new table called species_mean that has the mean for each variable for each Species,
species_group <- group_by(iris_data, Species)
species_mean <- summarise(species_group, Sepal.Length_mean = mean(Sepal.Length, na.rm = TRUE),
                            Sepal.Width_mean = mean(Sepal.Width, na.rm = TRUE),
                            Petal.Length_mean = mean(Petal.Length, na.rm = TRUE),
                            Petal.Width_mean = mean(Petal.Width, na.rm = TRUE))
species_mean         

#Create a data frame called iris_min with only the observations with at least 3 for Sep.Width and not 2.5 for Petal.Width.
iris_min <- filter(iris_data, Sepal.Width >= 3, Petal.Width != 2.5)
iris_min                          

#Create a date frame called iris_size with a column Sepal.Size which is small if Sepal.Length < 5, medium if Speal.Length >= 5 and < 6.5, and large if Sepal.Length >= 6.5.
iris_size <- mutate(iris_data,
                    Sepal.Size = 
                      case_when(
                        Sepal.Length < 5 ~ "small",
                        Sepal.Length >= 5 & Sepal.Length < 6.5 ~ "medium",
                        Sepal.Length >= 6.5 ~ "large"))
iris_size                          
                          
#Create a data frame called iris_rank which ranks all of the data by Petal.Length, where a rnking of 1 is the largest Petal.Length and order by ranking.
iris_rank <- arrange(iris_data, desc(Petal.Length))
iris_rank

#Read about the ?summarize_all() function and get a new table with the means and standard devisations for each species.
?summarize_all()

Mean_Sd_ForallSpecies <- 
  iris_data %>%
  group_by(Species) %>%
  summarize_all(list(Mean = mean, Std_Dev = sd))
Mean_Sd_ForallSpecies 
```

## Report
```{r}
#1. How much exercise do you think you should get in a week?

#Gillian - 8 hr
#Nick - 10 hrs
#Evan - 11 hrs
#Emma - 3 hrs
#Dawsyn - 4-5 hrs

#It was interesting seeing what different people said because the athletes that I asked said that you needed more exercise per week compared to the non-athletes that I asked. 

#2. Do you notice a difference in mental performance when you do not eat 3 meals a day?

#Gillian - Yes
#Nick - No
#Evan - Yes
#Emma - No
#Dawsyn - No

#A lot of the times that people said no they said that though they do not feel different if they don't get 3 meals, they said that the type of food they eat will effect them more.

#3. What are ways you could increase life expectancy?

#Gillian - Taking care of your mental health
#Nick - Taking care of your physical health
#Evan - Focusing on good nutrition
#Emma - Avoiding nicotine and tobacco
#Dawsyn - Drink lots of water and have a positive mindset

#These are all of the basic answers, but all together these would all be good answers if one person were to do all of these.
```

For my project I want to do something with sports, and I was think about using volleyball film to figure out how to get the most out of each play.

For example, I could find what percentage of time the hitter gets a kill in different situations.
Ex: 3 pass, perfect set... 2 pass, perfect set... 1 pass perfect set... 3 pass, bad set... 2 pass, bad set... 1 pass, bad set.
