---
title: "Task 21"
author: "Hannah Cope"
date: "11/17/2021"
output: 
  html_document:
    keep_md: True
    code_folding: 'hide'
---

#### Library Packages
```{r}
library(sf)
library(tidyverse)
library(maps)
library(lwgeom)
library(USAboundaries)
library(leaflet)
```

### Find the top 3 cities in each state with the highest populations
```{r}
contemporary_cities <- us_cities()

top_cities <- contemporary_cities %>%
  filter(state_name != 'Alaska', state_name != 'Hawaii') %>%
  group_by(state_name) %>%
  arrange(desc(population)) %>%
  slice(1:3)

number1 <- top_cities %>%
  slice(1:1)

number2 <- top_cities %>%
  slice(2:2)

number3 <- top_cities %>%
  slice(3:3)
```

### Plot the highest populations in each state
```{r}
leaflet() %>%
  addTiles() %>%
  addCircleMarkers(data = number1,
                   radius = 7,
                   color = "darkblue",
                   stroke = FALSE,
                   fillOpacity = 1,
                   popup = ~city,
                   label = ~population) %>%
  addCircleMarkers(data = number2,
                   radius = 5,
                   color = "blue",
                   stroke = FALSE,
                   fillOpacity = 1,
                   popup = ~city,
                   label = ~population) %>%
  addCircleMarkers(data = number3,
                   radius = 3,
                   color = "lightblue",
                   stroke = FALSE,
                   fillOpacity = 1,
                   popup = ~city,
                   label = ~population)
```

